// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcqO9D9FCRSI0CBzEW87FbN4GV8zZpxeI',
    appId: '1:325193637608:web:a1e11cd5261ee9708ef35d',
    messagingSenderId: '325193637608',
    projectId: 'servocontrol2-c5a8f',
    authDomain: 'servocontrol2-c5a8f.firebaseapp.com',
    databaseURL: 'https://servocontrol2-c5a8f-default-rtdb.firebaseio.com',
    storageBucket: 'servocontrol2-c5a8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiiBOMavZuuWIuHfeKL02DY2d5kgQXrts',
    appId: '1:325193637608:android:08126098e8581a858ef35d',
    messagingSenderId: '325193637608',
    projectId: 'servocontrol2-c5a8f',
    databaseURL: 'https://servocontrol2-c5a8f-default-rtdb.firebaseio.com',
    storageBucket: 'servocontrol2-c5a8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJG4y9eDhoIofeEZdNGg0zdQ-7FMto2T8',
    appId: '1:325193637608:ios:fc80730f2e5a20b28ef35d',
    messagingSenderId: '325193637608',
    projectId: 'servocontrol2-c5a8f',
    databaseURL: 'https://servocontrol2-c5a8f-default-rtdb.firebaseio.com',
    storageBucket: 'servocontrol2-c5a8f.firebasestorage.app',
    iosBundleId: 'com.example.solsiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJG4y9eDhoIofeEZdNGg0zdQ-7FMto2T8',
    appId: '1:325193637608:ios:fc80730f2e5a20b28ef35d',
    messagingSenderId: '325193637608',
    projectId: 'servocontrol2-c5a8f',
    databaseURL: 'https://servocontrol2-c5a8f-default-rtdb.firebaseio.com',
    storageBucket: 'servocontrol2-c5a8f.firebasestorage.app',
    iosBundleId: 'com.example.solsiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcqO9D9FCRSI0CBzEW87FbN4GV8zZpxeI',
    appId: '1:325193637608:web:de9c1f1cbe6e17a18ef35d',
    messagingSenderId: '325193637608',
    projectId: 'servocontrol2-c5a8f',
    authDomain: 'servocontrol2-c5a8f.firebaseapp.com',
    databaseURL: 'https://servocontrol2-c5a8f-default-rtdb.firebaseio.com',
    storageBucket: 'servocontrol2-c5a8f.firebasestorage.app',
  );
}
