// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbiKAyB-qugi2JITiKIoSGGTgUyysQRd4',
    appId: '1:314788925282:web:1d4abb92c35710d175263b',
    messagingSenderId: '314788925282',
    projectId: 'solsicontrol',
    authDomain: 'solsicontrol.firebaseapp.com',
    databaseURL: 'https://solsicontrol-default-rtdb.firebaseio.com',
    storageBucket: 'solsicontrol.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5SAKjeeYVJUf0BNaRv95VsK1rPjPkUi0',
    appId: '1:314788925282:android:c18d2553ae55b6a375263b',
    messagingSenderId: '314788925282',
    projectId: 'solsicontrol',
    databaseURL: 'https://solsicontrol-default-rtdb.firebaseio.com',
    storageBucket: 'solsicontrol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdchrq62cHoYSvfrCEJjd1pRojHEXQgh4',
    appId: '1:314788925282:ios:315d492ad602eaab75263b',
    messagingSenderId: '314788925282',
    projectId: 'solsicontrol',
    databaseURL: 'https://solsicontrol-default-rtdb.firebaseio.com',
    storageBucket: 'solsicontrol.firebasestorage.app',
    iosBundleId: 'com.example.solsiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdchrq62cHoYSvfrCEJjd1pRojHEXQgh4',
    appId: '1:314788925282:ios:315d492ad602eaab75263b',
    messagingSenderId: '314788925282',
    projectId: 'solsicontrol',
    databaseURL: 'https://solsicontrol-default-rtdb.firebaseio.com',
    storageBucket: 'solsicontrol.firebasestorage.app',
    iosBundleId: 'com.example.solsiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbiKAyB-qugi2JITiKIoSGGTgUyysQRd4',
    appId: '1:314788925282:web:0e5d1ce1e771e5d175263b',
    messagingSenderId: '314788925282',
    projectId: 'solsicontrol',
    authDomain: 'solsicontrol.firebaseapp.com',
    databaseURL: 'https://solsicontrol-default-rtdb.firebaseio.com',
    storageBucket: 'solsicontrol.firebasestorage.app',
  );

}